/*
 * products.js — the catalog, as data.
 *
 * This is the single source of truth for every product on the site. It is a
 * plain script (not a fetch), so it works from file:// and needs no build
 * step to be read by product.html.
 *
 * To add or edit a product, edit the array below. Then re-run
 *     python3 tools/build_listings.py
 * to re-bake the product cards into store.html and index.html, which stay as
 * static HTML so they are crawlable and survive JavaScript being off. The
 * per-category and per-merchant pages (category.html?id=<cat> and
 * merchant.html?id=<merchantSlug>) read this file at runtime via
 * js/listing-page.js, so they need no rebuild.
 *
 * Fields: id (URL slug, must stay stable — it is the permalink), name, cat,
 * catLabel, merchant, merchantSlug, url (merchant product page), img.
 * price is optional — omit it for brand/landing pages that have no single
 * price, and the UI hides the price line rather than inventing one.
 */
window.PRODUCTS = [
  {"id": "bc-hamper", "name": "Large Bear Laundry Hamper, Nursery & Kids Room Toy & Laundry Storage", "cat": "dorm-living-essentials", "catLabel": "Dorm & Living Essentials", "merchant": "Best Choice", "merchantSlug": "best-choice", "url": "https://bestchoiceproducts.sjv.io/c/5891219/2899144/33479?prodsku=46201746489530&u=https%3A%2F%2Fbestchoiceproducts.com%2Fproducts%2Fkids-large-bear-laundry-hamper-nursery-kids-room-toy-laundry-storage&intsrc=APIG_23231", "img": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/7cec83c3-edbb-4600-bc91-eb1bcf721e2d.jpg", "price": 80.0},
  {"id": "bc-games", "name": "Large Double-Sided Dart Board, Sticky Ball Axe Star Throwing Game", "cat": "dorm-living-essentials", "catLabel": "Dorm & Living Essentials", "merchant": "Best Choice", "merchantSlug": "best-choice", "url": "https://bestchoiceproducts.sjv.io/c/5891219/2899144/33479?prodsku=42762750820538&u=https%3A%2F%2Fbestchoiceproducts.com%2Fproducts%2Flarge-double-sided-dart-board-sticky-ball-axe-star-throwing-game&intsrc=APIG_23231", "img": "https://cdn.shopify.com/s/files/1/0636/7991/files/SKY7226LRG-1.jpg?v=1698696691", "price": 30.0},
  {"id": "bc-ceramic", "name": "Best Choice Products - 3Pc Ceramic Halloween Trees, Pre-Lit Hand Painted Pencil Tabletop Holiday Decoration LEDs - Black w/ Orange, Purple & White Lights", "cat": "living-social-spaces", "catLabel": "Living & Social Spaces", "merchant": "Best Choice", "merchantSlug": "best-choice", "url": "https://bestchoiceproducts.sjv.io/c/5891219/2899144/33479?prodsku=46173156540602&u=https%3A%2F%2Fbestchoiceproducts.com%2Fproducts%2F3pc-ceramic-halloween-trees-pre-lit-pencil-tabletop-decoration-leds&intsrc=APIG_23231", "img": "https://cdn.shopify.com/s/files/1/0636/7991/files/SKY11477LRG-1.jpg?v=1784913018", "price": 80.0},
  {"id": "bc-storage", "name": "Best Choice Products Round Storage Basket w/ Handles Handwoven Water Hyacinth Plant Holder Storage Organizer Tote Bin for Bedroom Living Room Bathroom", "cat": "bathroom", "catLabel": "Bathroom", "merchant": "Best Choice", "merchantSlug": "best-choice", "url": "https://bestchoiceproducts.sjv.io/c/5891219/2899144/33479?prodsku=8322537226426&u=https%3A%2F%2Fbestchoiceproducts.com%2Fproducts%2Fround-storage-basket-w-handles-handwoven-water-hyacinth-tote&intsrc=APIG_23231", "img": "https://cdn.shopify.com/s/files/1/0636/7991/files/SKY10993LRG-1.jpg?v=1769689214", "price": 70.0},
  {"id": "bc-chairs", "name": "Bayview Dining Chairs Set of 2 with Cushion, Armrest, Wooden Frame", "cat": "living-social-spaces", "catLabel": "Living & Social Spaces", "merchant": "Best Choice", "merchantSlug": "best-choice", "url": "https://bestchoiceproducts.sjv.io/c/5891219/2899144/33479?prodsku=46155409916090&u=https%3A%2F%2Fbestchoiceproducts.com%2Fproducts%2Fset-of-2-indoor-outdoor-bayview-dining-chairs-with-arms-all-weather-rope&intsrc=APIG_23231", "img": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/d252df8f-b442-4baa-8039-7e6adb04399a.jpg", "price": 200.0},
  {"id": "vans-crosspath", "name": "Vans Crosspath XC GORE-TEXShoes ", "cat": "personal-lifestyle", "catLabel": "Personal Lifestyle", "merchant": "Vans", "merchantSlug": "vans", "url": "https://vans.pxf.io/c/5891219/3796160/48802?prodsku=VN000DAMWHT_VN%3A000DAM%3AWHT%3A055%3AM%3A1%3A&u=https%3A%2F%2Fwww.vans.com%2Fen-us%2Fp%2Fshoes%2Fcrosspath-6135%2Fcrosspath-xc-gore-tex-shoe-VN000DAMWHT%3F%26utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_campaign%3Dorganic-shopping&intsrc=APIG_31325", "img": "https://assets.vans.com/images/t_img/c_fill,g_center,f_auto,h_573,e_unsharp_mask:100,w_458/dpr_2.0/v1781130631/VN000EKHFS8-HERO/Crosspath-XC-GORETEX-Shoe-VANS-HERO.png", "price": 180.0},
  {"id": "belkin-tech-accessories-weekly-deals", "name": "Belkin Tech Accessories — Weekly Deals", "cat": "academic-essentials", "catLabel": "Academic Essentials", "merchant": "Belkin", "merchantSlug": "belkin", "url": "https://www.belkin.com/sale/", "img": "https://www.belkin.com/on/demandware.static/-/Sites/default/dw58ddf68f/2026-Falcon-gaming-campaign-dotcom-homepage-banner-03-mobile-373x400-us.jpg", "note": "Sale landing page - no single product price"},
  {"id": "modern-threads-wavy-luxury-spa-6-pc-quick-dry", "name": "Modern Threads Wavy Luxury Spa 6-pc. Quick-dry Towel Set", "cat": "bathroom", "catLabel": "Bathroom", "merchant": "Bed Bath & Beyond", "merchantSlug": "bed-bath-beyond", "url": "https://www.bedbathandbeyond.com/Bedding-Bath/Amrapur-Overseas-Wavy-Luxury-Spa-Collection-6-piece-Quick-Dry-Towel-Set/10122652/product.html", "img": "https://ak1.ostkcdn.com/images/products/10122652/Wavy-Luxury-Spa-Collection-6-Piece-Quick-Dry-Towel-Set-1c10c465-1170-4369-9174-8f6fe790b5cc_600.jpg", "price": 33.96, "note": "Price is \"From $33.96\" (varies by color)"},
  {"id": "gemini-crypto-trading-earn-platform", "name": "Gemini — Crypto Trading & Earn Platform", "cat": "financial-services", "catLabel": "Financial Services", "merchant": "Gemini", "merchantSlug": "gemini", "url": "https://www.gemini.com/", "img": "https://www.gemini.com/static/images/og-meta-v2.png", "note": "Brand landing page - no product price"},
  {"id": "resume-io-free-resume-builder", "name": "Resume.io — Free Resume Builder", "cat": "financial-services", "catLabel": "Financial Services", "merchant": "Resume.io", "merchantSlug": "resume-io", "url": "https://resume.io/", "img": "https://s3.resume.io/uploads/country/og_image/2/OG.png", "note": "Brand landing page - no product price"},
  {"id": "cloudfield-bamboo-sunglasses-blue-light-glasses", "name": "Cloudfield — Bamboo Sunglasses & Blue Light Glasses", "cat": "personal-lifestyle", "catLabel": "Personal Lifestyle", "merchant": "Cloudfield", "merchantSlug": "cloudfield", "url": "https://www.cloudfield.co/", "img": "https://static.wixstatic.com/media/d2d7a5_25b1c6b1276c478b9697481d39c2fa50~mv2.jpg", "note": "Brand landing page - no single product price"},
];
