/*
 * products.js — the catalog, as data.
 *
 * This is the single source of truth for every product on the site. It is a
 * plain script (not a fetch), so it works from file:// and needs no build
 * step to be read by product.html.
 *
 * To add or edit a product, edit the array below. Then re-run
 *     python3 tools/build_listings.py
 * to re-bake the product cards into store.html and index.html, which stay as
 * static HTML so they are crawlable and survive JavaScript being off. The
 * per-category and per-merchant pages (category.html?id=<cat> and
 * merchant.html?id=<merchantSlug>) read this file at runtime via
 * js/listing-page.js, so they need no rebuild.
 *
 * Fields: id (URL slug, must stay stable — it is the permalink), name, cat,
 * catLabel, merchant, merchantSlug, url (merchant product page), img.
 * price is optional — omit it for brand/landing pages that have no single
 * price, and the UI hides the price line rather than inventing one.
 */
window.PRODUCTS = [
  {"id": "acer-chromebook-315-15-6-inch-laptop", "name": "Acer Chromebook 315 15.6 inch Laptop Intel Processor N4500 4GB RAM 64GB eMMC Pure Silver", "cat": "academic-essentials", "catLabel": "Academic Essentials", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/Acer-Chromebook-315-15-6-inch-Laptop-Intel-Processor-N4500-4GB-RAM-64GB-eMMC-Pure-Silver-ChromeOS/3193557250?classType=VARIANT&athbdg=L1103&from=/search", "img": "https://i5.walmartimages.com/seo/Acer-Chromebook-315-15-6-inch-Laptop-Intel-Processor-N4500-4GB-RAM-64GB-eMMC-Pure-Silver-ChromeOS_e9b49ec2-6204-434c-841b-e4dbd1846431.c146aa580b8b9806ef9eb45067ae5094.jpeg", "price": 199.0},
  {"id": "acer-chromebook-315-15-6-inch-laptop-copy", "name": "Acer3 Chromebook 315 15.6 inch Laptop Intel Processor N4500 4GB RAM 64GB eMMC Pure Silver (copy)", "cat": "academic-essentials", "catLabel": "Academic Essentials", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/Acer-Chromebook-315-15-6-inch-Laptop-Intel-Processor-N4500-4GB-RAM-64GB-eMMC-Pure-Silver-ChromeOS/3193557250?classType=VARIANT&athbdg=L1103&from=/search", "img": "https://i5.walmartimages.com/seo/Acer-Chromebook-315-15-6-inch-Laptop-Intel-Processor-N4500-4GB-RAM-64GB-eMMC-Pure-Silver-ChromeOS_e9b49ec2-6204-434c-841b-e4dbd1846431.c146aa580b8b9806ef9eb45067ae5094.jpeg", "price": 199.0},
  {"id": "acer-chromebook-315-15-6-inch-laptop-copy-2", "name": "Acer4 Chromebook 315 15.6 inch Laptop Intel Processor N4500 4GB RAM 64GB eMMC Pure Silver (copy) (copy)", "cat": "academic-essentials", "catLabel": "Academic Essentials", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/Acer-Chromebook-315-15-6-inch-Laptop-Intel-Processor-N4500-4GB-RAM-64GB-eMMC-Pure-Silver-ChromeOS/3193557250?classType=VARIANT&athbdg=L1103&from=/search", "img": "https://i5.walmartimages.com/seo/Acer-Chromebook-315-15-6-inch-Laptop-Intel-Processor-N4500-4GB-RAM-64GB-eMMC-Pure-Silver-ChromeOS_e9b49ec2-6204-434c-841b-e4dbd1846431.c146aa580b8b9806ef9eb45067ae5094.jpeg", "price": 199.0},
  {"id": "belkin-tech-accessories-weekly-deals", "name": "Belkin Tech Accessories — Weekly Deals", "cat": "academic-essentials", "catLabel": "Academic Essentials", "merchant": "Belkin", "merchantSlug": "belkin", "url": "https://www.belkin.com/sale/", "img": "https://www.belkin.com/on/demandware.static/-/Sites/default/dw58ddf68f/2026-Falcon-gaming-campaign-dotcom-homepage-banner-03-mobile-373x400-us.jpg", "note": "Sale landing page - no single product price"},
  {"id": "hp-essential-14-laptop-intel-n150-8gb", "name": "HP Essential 14\" Laptop, Intel N150, 8GB RAM, 128GB eMMC, Windows 11 Home, Pink", "cat": "academic-essentials", "catLabel": "Academic Essentials", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/HP-Essential-14-Laptop-Intel-N150-8GB-RAM-128GB-eMMC-Windows-11-Home-Pink/20353606354?classType=VARIANT&athbdg=L1900&adsRedirect=true", "img": "https://i5.walmartimages.com/seo/HP-Essential-14-Laptop-Intel-N150-8GB-RAM-128GB-eMMC-Windows-11-Home-Pink_e4c123b3-41b9-4f9d-8c1e-1d6732c9c708.fec21fb7da540e7a8b40f503dfe57492.jpeg", "price": 346.79},
  {"id": "hyperx-omen-15-3-wuxga-165hz-2k", "name": "HyperX OMEN 15.3\" WUXGA 165Hz 2K IPS Gaming Laptop, Intel Core 5 210H, NVIDIA RTX 5050, 16GB, 512GB SSD, Windows 11 - Iridescent Black", "cat": "academic-essentials", "catLabel": "Academic Essentials", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/HP-OMEN-Gaming-Notebook-15-3-2K-Intel-Core-5-16-RAM-512-SSD-Nvidia-RTX-5050-Black/18153321068?adsRedirect=true", "img": "https://i5.walmartimages.com/seo/HP-OMEN-Gaming-Notebook-15-3-2K-Intel-Core-5-16-RAM-512-SSD-Nvidia-RTX-5050-Black_7dc98395-ad1e-4253-938c-c98f3e49e7ae.9a049b3eb02b12719f8851a2396c3ba3.jpeg", "price": 1199.0},
  {"id": "lenovo-legion-5i-15-1-wqxga-165hz", "name": "Lenovo Legion 5i 15.1\" WQXGA 165Hz Gaming Laptop, Core i7-14700HX, NVIDIA Geforce RTX 5060, 16GB RAM, 1TB SSD - 3 Months Microsoft 365 Personal", "cat": "academic-essentials", "catLabel": "Academic Essentials", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/ASUS-Vivobook-S-14-Copilot-PC-14-WUXGA-OLED-Windows-Laptop-Intel-Core-Ultra-7-Series-2-258V-AI-PC-Intel-Evo-32GB-RAM-1TB-SSD-Black/7447569796?adsRedirect=true", "img": "https://i5.walmartimages.com/asr/e3399d0c-c753-43fb-af6f-4574e16deff0.6b26caddfcdbffef1e108ff7b26a5927.jpeg", "price": 899.0, "note": "URL now resolves to a Lenovo Legion 5i, NOT the ASUS Vivobook - link needs replacing"},
  {"id": "crocodile-memory-foam-bath-rug-19-x", "name": "Crocodile Memory Foam Bath Rug, 19\" x 30\"", "cat": "bathroom", "catLabel": "Bathroom", "merchant": "Macy's", "merchantSlug": "macys", "url": "https://www.macys.com/shop/product/lacoste-home-crocodile-memory-foam-bath-rug-19-x-30?ID=4490610&swatchColor=Sand", "img": "https://slimages.macysassets.com/is/image/MCY/products/0/optimized/8251500_fpx.tif", "price": 40.0},
  {"id": "modern-threads-wavy-luxury-spa-6-pc-quick-dry", "name": "Modern Threads Wavy Luxury Spa 6-pc. Quick-dry Towel Set", "cat": "bathroom", "catLabel": "Bathroom", "merchant": "Bed Bath & Beyond", "merchantSlug": "bed-bath-beyond", "url": "https://www.bedbathandbeyond.com/Bedding-Bath/Amrapur-Overseas-Wavy-Luxury-Spa-Collection-6-piece-Quick-Dry-Towel-Set/10122652/product.html", "img": "https://ak1.ostkcdn.com/images/products/10122652/Wavy-Luxury-Spa-Collection-6-Piece-Quick-Dry-Towel-Set-1c10c465-1170-4369-9174-8f6fe790b5cc_600.jpg", "price": 33.96, "note": "Price is \"From $33.96\" (varies by color)"},
  {"id": "quick-dry-striped-bath-towel-macy-s", "name": "Quick Dry Striped Bath Towel, Macy's Exclusive", "cat": "bathroom", "catLabel": "Bathroom", "merchant": "Macy's", "merchantSlug": "macys", "url": "https://www.macys.com/shop/product/arch-studio-quick-dry-striped-bath-towels-macys-exclusive?ID=26424805&swatchColor=Pinkberry+Stripe", "img": "https://slimages.macysassets.com/is/image/MCY/products/7/optimized/36203927_fpx.tif", "price": 18.0},
  {"id": "tara-4-pc-bath-accessory-set", "name": "Tara 4-Pc. Bath Accessory Set", "cat": "bathroom", "catLabel": "Bathroom", "merchant": "Macy's", "merchantSlug": "macys", "url": "https://www.macys.com/shop/product/martha-stewart-tara-4-pc.-bath-accessory-set?ID=18836299&swatchColor=Gray", "img": "https://slimages.macysassets.com/is/image/MCY/products/2/optimized/28645722_fpx.tif", "price": 67.0},
  {"id": "animal-house-national-lampoon-s-men-s", "name": "Animal House National Lampoon's Men's Bluto 7 Years Of College Short Sleeve T-Shirt", "cat": "bedroom-study", "catLabel": "Bedroom & Study", "merchant": "Macy's", "merchantSlug": "macys", "url": "https://www.macys.com/shop/product/animal-house-national-lampoons-mens-bluto-7-years-of-college-short-sleeve-t-shirt?ID=10163054", "img": "https://slimages.macysassets.com/is/image/MCY/products/5/optimized/14906065_fpx.tif", "price": 24.99},
  {"id": "back-to-college-dorm-room-essentials-8-pc", "name": "Back to College Dorm Room Essentials 8-Pc. Bed & Bath Kit, Twin XL", "cat": "bedroom-study", "catLabel": "Bedroom & Study", "merchant": "Macy's", "merchantSlug": "macys", "url": "https://www.macys.com/shop/product/complete-back-to-college-dorm-room-essentials-kit-bed-bath-twin-xl?ID=23734251", "img": "https://slimages.macysassets.com/is/image/MCY/products/1/optimized/33621291_fpx.tif", "price": 84.47},
  {"id": "bcooss-led-desk-lamp-for-an-office", "name": "BCOOSS Led Desk Lamp for an Office in Home with Pen Holder and Wireless Charger- 3 Modes Dimmable LED Table Lamp with Flexible Gooseneck", "cat": "bedroom-study", "catLabel": "Bedroom & Study", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/BCOOSS-Led-Desk-Lamp-for-an-Office-in-Home-with-Pen-Holder-and-Wireless-Charger-3-Modes-Dimmable-LED-Table-Lamp-with-Flexible-Gooseneck/1731778368?classType=VARIANT&from=/search", "img": "https://i5.walmartimages.com/seo/BCOOSS-Led-Desk-Lamp-for-an-Office-in-Home-with-Pen-Holder-and-Wireless-Charger-3-Modes-Dimmable-LED-Table-Lamp-with-Flexible-Gooseneck_d61cce55-54b4-4551-8858-f0de1d057cad.4f9a61dd55dd6e48f2cc0c801f235c23.jpeg", "price": 16.99},
  {"id": "basic-necessities---bedding-package", "name": "Basic Necessities - Bedding Package", "cat": "dorm-living-essentials", "catLabel": "Dorm & Living Essentials", "merchant": "Dormco", "merchantSlug": "dormco", "url": "https://www.dormco.com/Basic_Necessities_College_Dorm_Bedding_Package_p/basic-necess.htm", "img": "https://cdn11.bigcommerce.com/s-9uidjadyqm/images/stencil/1280x1280/products/3606/60279/basic_necessities-cherry_red_nightfall_navy2__65350.1744310315.jpg?c=1", "price": 127.06},
  {"id": "elastic-wrap-around-dorm-bed-skirt-easy", "name": "Elastic Wrap Around Dorm Bed Skirt, Easy Fit 32-42\" Extra Long Drop", "cat": "dorm-living-essentials", "catLabel": "Dorm & Living Essentials", "merchant": "Macy's", "merchantSlug": "macys", "url": "https://www.macys.com/shop/product/cgk-unlimited-elastic-wrap-around-dorm-bed-skirt-easy-fit-32-42-extra-long-drop?ID=28140352&swatchColor=Dark+grey+32", "img": "https://slimages.macysassets.com/is/image/MCY/products/8/optimized/38748688_fpx.tif", "price": 31.15},
  {"id": "fully-loaded-pack---dorm-bedding-essentials-3", "name": "Fully-Loaded Pack - Dorm Bedding + Essentials #3 Package", "cat": "dorm-living-essentials", "catLabel": "Dorm & Living Essentials", "merchant": "Dormco", "merchantSlug": "dormco", "url": "https://www.dormco.com/DormCo_College_Dorm_Package_3_Fully_Loaded_Pack_p/buck2-dcdp1.htm", "img": "https://cdn11.bigcommerce.com/s-9uidjadyqm/images/stencil/1280x1280/products/4891/10255/BUCK2-DCDP1-2__95951.1740770457.jpg?c=1", "price": 224.14},
  {"id": "the-44-piece-college-dorm-essentials-set--", "name": "The 44-Piece College Dorm Essentials Set - Totally Complete", "cat": "dorm-living-essentials", "catLabel": "Dorm & Living Essentials", "merchant": "Dormco", "merchantSlug": "dormco", "url": "https://www.dormco.com/The_44_Piece_College_Dorm_Essentials_Set_Totall_p/top44-essentials.htm", "img": "https://cdn11.bigcommerce.com/s-9uidjadyqm/images/stencil/1280x1280/products/14800/60275/The_44-Piece_Package_-_Orchid_Petal_Alloy2_3__86283.1744309860.jpg?c=1", "price": 198.24},
  {"id": "yucca-hint-of-mint-full-comforter--", "name": "Yucca/Hint of Mint Full Comforter - Oversized Full XL Bedding", "cat": "dorm-living-essentials", "catLabel": "Dorm & Living Essentials", "merchant": "Dormco", "merchantSlug": "dormco", "url": "https://www.dormco.com/Reversible_Full_College_Comforter_Yucca_and_Mint_p/crys-micro-rev-full-hmyu.htm", "img": "https://cdn11.bigcommerce.com/s-9uidjadyqm/images/stencil/1280x1280/products/6788/15616/CRYS-MICRO-REV-FULL-HMYU-2__76982.1740770737.jpg?c=1", "price": 68.2},
  {"id": "gemini-crypto-trading-earn-platform", "name": "Gemini — Crypto Trading & Earn Platform", "cat": "financial-services", "catLabel": "Financial Services", "merchant": "Gemini", "merchantSlug": "gemini", "url": "https://www.gemini.com/", "img": "https://www.gemini.com/static/images/og-meta-v2.png", "note": "Brand landing page - no product price"},
  {"id": "resume-io-free-resume-builder", "name": "Resume.io — Free Resume Builder", "cat": "financial-services", "catLabel": "Financial Services", "merchant": "Resume.io", "merchantSlug": "resume-io", "url": "https://resume.io/", "img": "https://s3.resume.io/uploads/country/og_image/2/OG.png", "note": "Brand landing page - no product price"},
  {"id": "cuisinart-air-fryers-at-macys", "name": "Cuisinart Air Fryers at Macy’s", "cat": "kitchen-dining", "catLabel": "Kitchen & Dining", "merchant": "Macy's", "merchantSlug": "macys", "url": "https://www.macys.com/shop/featured/air-fryer/Brand,Electrics_type,Price/Cuisinart,Air%20Fryer,50%257C100", "img": "https://slimages.macysassets.com/is/image/MCY/products/4/optimized/19735034_fpx.tif?qlt=70,0&resMode=sharp2&op_usm=1.75,0.3,2,0&fmt=webp&wid=684&hei=834", "note": "Filtered category listing, not a single product page - no single price"},
  {"id": "frigidaire-retro-12-can-mini-beverage-skincare", "name": "Frigidaire Retro 12 Can Mini Beverage/Skincare Cooler, Black, Compact Refrigerators", "cat": "kitchen-dining", "catLabel": "Kitchen & Dining", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/Frigidaire-Retro-12-Can-Mini-Beverage-Skincare-Cooler-Black-Compact-Refrigerators/3056868659?classType=VARIANT&from=/search", "img": "https://i5.walmartimages.com/seo/Frigidaire-Retro-12-Can-Mini-Beverage-Skincare-Cooler-Black-Compact-Refrigerators_d0d90183-92ef-450f-bf05-608cbbc8f04f.019b22ef8a548f96c88a3d7a6f767c9d.jpeg", "price": 47.92},
  {"id": "mainstays-0-7-cu-ft-countertop-microwave", "name": "Mainstays 0.7 cu ft Countertop Microwave Oven, 700 W, Black, New", "cat": "kitchen-dining", "catLabel": "Kitchen & Dining", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/Mainstays-0-7-Cu-ft-Countertop-Microwave-Oven-700-Watts-Black/5125973778?classType=VARIANT&athbdg=L1300&from=/search", "img": "https://i5.walmartimages.com/seo/Mainstays-0-7-Cu-ft-Countertop-Microwave-Oven-700-Watts-Black_70772fdd-b5cf-496b-bddf-f0701146991b.8b3ed6cc5c052a2828cb1d919721442b.jpeg", "price": 49.0},
  {"id": "3-pack-clorox-disinfecting-cleaning-wipes-to", "name": "(3 pack) Clorox Disinfecting Cleaning Wipes To Go Pack, Bleach Free, Fresh Scent, 9 Count", "cat": "laundry-cleaning", "catLabel": "Laundry & Cleaning", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/3-pack-Clorox-Disinfecting-Wipes-on-the-Go-Bleach-Free-Travel-Wipes-Fresh-Scent-9-Count/14075774699?from=/search", "img": "https://i5.walmartimages.com/seo/3-pack-Clorox-Disinfecting-Wipes-on-the-Go-Bleach-Free-Travel-Wipes-Fresh-Scent-9-Count_d93cf38a-1528-47f6-b484-01b92e59b463.3ebbc7aad560e22bed38639dfa402711.jpeg", "price": 3.0},
  {"id": "clorox-disinfecting-cleaning-wipes-variety-pack-bleach", "name": "Clorox Disinfecting Cleaning Wipes Variety Pack, Bleach Free, Fresh Scent and Crisp Lemon, 35 Count Each, Pack of 3", "cat": "laundry-cleaning", "catLabel": "Laundry & Cleaning", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/Clorox-Bleach-Free-Disinfecting-and-Cleaning-Wipes-35-Count-Each-3-Pack/15543972?classType=REGULAR&athbdg=L1600&from=/search", "img": "https://i5.walmartimages.com/seo/Clorox-Bleach-Free-Disinfecting-and-Cleaning-Wipes-35-Count-Each-3-Pack_f154a92c-76d4-4eb3-bb57-e925b802b63e.684528263138e323576350a7cc24a68b.jpeg", "price": 7.28},
  {"id": "costway-5-5lbs-portable-mini-compact-washing", "name": "Costway 5.5lbs Portable Mini Compact Washing Machine Electric Laundry Spin Washer Dryer Blue", "cat": "laundry-cleaning", "catLabel": "Laundry & Cleaning", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/Costway-5-5lbs-Portable-Mini-Compact-Washing-Machine-Electric-Laundry-Spin-Washer-Dryer-Blue/320496317", "img": "https://i5.walmartimages.com/seo/Costway-5-5lbs-Portable-Mini-Compact-Washing-Machine-Electric-Laundry-Spin-Washer-Dryer-Blue_015931e4-3cd7-4c5a-93c8-295096a91fdf_1.080ad2046712dcc30f78d75549815893.jpeg", "price": 65.99},
  {"id": "home-logic-2-bushel-rolling-plastic-laundry", "name": "Home Logic 2 Bushel Rolling Plastic Laundry Hamper with Pop-up Handle, White, Adult", "cat": "laundry-cleaning", "catLabel": "Laundry & Cleaning", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/Home-Logic-2-Bushel-Rolling-Plastic-Laundry-Hamper-with-Pop-up-Handle-White-Adult-Tween/173128053?classType=VARIANT&athbdg=L1600&adsRedirect=true", "img": "https://i5.walmartimages.com/seo/Home-Logic-2-Bushel-Rolling-Plastic-Laundry-Hamper-with-Pop-up-Handle-White-Adult-Tween_81c847a3-bc83-424a-929f-d9a162cfaed2.e7cfbb95ba12278bacb46cb57798bad3.jpeg", "price": 16.48},
  {"id": "juniper-clean-single-surface-cleaning-wipes-bleach", "name": "Juniper CLEAN Single Surface Cleaning Wipes Bleach Free, Thick & Large Dispose, All-Purpose Cleaner for Bathroom, Kitchen, Office, 100 Count Soft Flow, Biodegradable, Citrus Scent", "cat": "laundry-cleaning", "catLabel": "Laundry & Cleaning", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/Juniper-CLEAN-Single-Surface-Cleaning-Wipes-Bleach-Free-Thick-Large-Dispose-All-Purpose-Cleaner-Bathroom-Kitchen-Office-100-Count-Soft-Flow-Biodegrad/17129009583?classType=VARIANT&adsRedirect=true", "img": "https://i5.walmartimages.com/seo/Juniper-CLEAN-Single-Surface-Cleaning-Wipes-Bleach-Free-Thick-Large-Dispose-All-Purpose-Cleaner-Bathroom-Kitchen-Office-100-Count-Soft-Flow-Biodegrad_721b2b79-1622-4b97-b3b1-951a23eab34f.874e04f7d8122f68d271a3e9962f5f42.jpeg", "note": "Out of stock - no price shown on page"},
  {"id": "lysol-disinfecting-wipes-all-purpose-cleaner-multi", "name": "Lysol Disinfecting Wipes, All Purpose Cleaner, Multi Surface Antibacterial Cleaning Wipes, Cleaning Supplies, Lavender & Cotton Blossom Scent, 80 Count", "cat": "laundry-cleaning", "catLabel": "Laundry & Cleaning", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/LYSOL-LDW-L-CB-80CT/9112461711?classType=VARIANT&from=/search", "img": "https://i5.walmartimages.com/seo/LYSOL-LDW-L-CB-80CT_28c886ec-6447-4d89-9369-aa99900af621.840bfb09a2a9a82b5d7c7c38a4581caf.jpeg", "price": 5.22},
  {"id": "mainstays-mesh-pop-up-hamper-collapsible-holds-2", "name": "Mainstays Mesh Pop-up Hamper, Collapsible, Holds 2 Loads, White, Adult", "cat": "laundry-cleaning", "catLabel": "Laundry & Cleaning", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/Mainstays-Mesh-Pop-Up-Hamper-Laundry-and-Home-Organization/136878840?classType=VARIANT&athbdg=L1105&from=/search", "img": "https://i5.walmartimages.com/seo/Mainstays-Mesh-Pop-Up-Hamper-Laundry-and-Home-Organization_c5028b01-a648-4df6-9afb-824baa593d31.656e5d1810911e21b284461b768acd10.jpeg", "price": 4.48},
  {"id": "17-rectangle-stained-glass-storage-bin", "name": "17\" Rectangle Stained Glass Storage Bin", "cat": "living-social-spaces", "catLabel": "Living & Social Spaces", "merchant": "Macy's", "merchantSlug": "macys", "url": "https://www.macys.com/shop/product/design-imports-17-rectangle-stained-glass-storage-bin?ID=9015467&swatchColor=Turquoise", "img": "https://slimages.macysassets.com/is/image/MCY/products/3/optimized/12718953_fpx.tif", "price": 35.0},
  {"id": "comfy-bean-bag-chair-with-memory-foam", "name": "Comfy Bean Bag Chair with Memory Foam, Cozy Lounge Chair for Dorm, Bedroom, Living Room", "cat": "living-social-spaces", "catLabel": "Living & Social Spaces", "merchant": "Macy's", "merchantSlug": "macys", "url": "https://www.macys.com/shop/product/comfy-bean-bag-chair-with-memory-foam-cozy-lounge-chair-for-dorm-bedroom-living-room-the-pop-home?ID=20703732&swatchColor=Pink++teddy", "img": "https://slimages.macysassets.com/is/image/MCY/products/0/optimized/31145560_fpx.tif", "price": 143.99},
  {"id": "junovo-fluffy-oval-rug-soft-tie-dye", "name": "Junovo Fluffy Oval Rug Soft Tie Dye Area Rugs Shaggy Colorful Carpet Plush Bedside Carpet for Teen Dorm Baby Nursery,2.6 x 5.3ft,Pink", "cat": "living-social-spaces", "catLabel": "Living & Social Spaces", "merchant": "Walmart", "merchantSlug": "walmart", "url": "https://www.walmart.com/ip/Junovo-Fluffy-Oval-Rug-Soft-Tie-Dye-Area-Rugs-Shaggy-Colorful-Carpet-Plush-Bedside-Carpet-for-Teen-Dorm-Baby-Nursery-2-6-x-5-3ft-Pink/3575222099?classType=VARIANT&athbdg=L1600&from=/search", "img": "https://i5.walmartimages.com/seo/Junovo-Fluffy-Oval-Rug-Soft-Tie-Dye-Area-Rugs-Shaggy-Colorful-Carpet-Plush-Bedside-Carpet-for-Teen-Dorm-Baby-Nursery-2-6-x-5-3ft-Pink_97ce575b-a6e1-4a91-8497-a9323cfc78bc.c1a9eab43dd80fd6376b813e5b32c2bc.jpeg", "price": 23.99},
  {"id": "cloudfield-bamboo-sunglasses-blue-light-glasses", "name": "Cloudfield — Bamboo Sunglasses & Blue Light Glasses", "cat": "personal-lifestyle", "catLabel": "Personal Lifestyle", "merchant": "Cloudfield", "merchantSlug": "cloudfield", "url": "https://www.cloudfield.co/", "img": "https://static.wixstatic.com/media/d2d7a5_25b1c6b1276c478b9697481d39c2fa50~mv2.jpg", "note": "Brand landing page - no single product price"},
  {"id": "women-s-jester-backpack", "name": "Women's Jester Backpack", "cat": "personal-lifestyle", "catLabel": "Personal Lifestyle", "merchant": "Macy's", "merchantSlug": "macys", "url": "https://www.macys.com/shop/product/the-north-face-womens-jester-backpack?ID=21690409&swatchColor=TNF+Black", "img": "https://slimages.macysassets.com/is/image/MCY/products/2/optimized/19176692_fpx.tif", "price": 90.0},
];
